version: '3'
services:
  service_discovery:
    build: ./ServiceDiscovery/service-discovery
    ports:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  gateway:
    build: ./Gateway/gateway
    ports:
      - "8080:8080"
      - "7070"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - service_discovery

  ranking_service:
    build: ./ranking_service
    ports: 
      - "8080"
    depends_on:
      - ranking_service_database
      - redis_game_cache
      - service_discovery
      - gateway
    environment:
      POSTGRES_HOST: ranking_service_repo
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  game_service:
    build: ./game_service
    ports:
      - "7070"
    depends_on:
      - game_history_database
      - redis_game_cache
      - service_discovery
      - gateway
    environment:
      POSTGRES_HOST: game_history_database
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr

  ranking_service_database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ranking_service_repo
    volumes:
      - postgres_ranking_data:/var/lib/postgresql/data
    ports:
      - "5432"

  redis_game_cache:
    image: redis:alpine
    restart: always
    ports:
      - '6379'
    volumes: 
      - redis_game_cache:/data

  game_history_database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: game_history_repo
    volumes:
      - postgres_game_data:/var/lib/postgresql/data
    ports:
      - "5432"

volumes:
  postgres_ranking_data:
  postgres_game_data:
  redis_game_cache: